<a href="https://colab.research.google.com/github/trochim/pytorchlearning/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSOR MATH OPERATIONS**


- Add, Subtract, Multiply, Divide, Reminders, Exponents
- Shorthand and uh, longhand
- Reassignment






In [1]:
import torch
import numpy as np

In [23]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


In [4]:
## Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
## Add functiom
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
## Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [9]:
## Sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [10]:
## Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [11]:
## Mul function
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [12]:
## Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
## Div function
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
## Remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [17]:
## Remainder function
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [18]:
## Exponents /power
torch,pow(tensor_a, tensor_b)

(<module 'torch' from '/usr/local/lib/python3.10/dist-packages/torch/__init__.py'>,
 tensor([    1,    64,  2187, 65536]))

In [19]:
## another way to write longhand/function
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [20]:
## Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [27]:
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([11, 14, 17, 20])

In [28]:
tensor_a


tensor([11, 14, 17, 20])