<a href="https://colab.research.google.com/github/trochim/pytorchlearning/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors


*   List item
*   List item



**IMPORT**

In [1]:
import torch


In [2]:
import numpy as np

**LIST**

In [4]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**NUMPY**

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.04145786, 0.3715379 , 0.52907452, 0.45978519],
       [0.01441099, 0.78382105, 0.46065219, 0.93165352],
       [0.17930147, 0.37843988, 0.5949401 , 0.22839917]])

In [6]:
np1.dtype


dtype('float64')

**TENSORS**

In [11]:
tensor_2d = torch.rand(3,4)
tensor_2d
##tensor_2d.dtype

tensor([[0.5471, 0.6787, 0.8819, 0.3487],
        [0.4933, 0.5301, 0.8235, 0.9073],
        [0.9523, 0.5616, 0.7657, 0.8801]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
## Create tensorout of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0415, 0.3715, 0.5291, 0.4598],
        [0.0144, 0.7838, 0.4607, 0.9317],
        [0.1793, 0.3784, 0.5949, 0.2284]], dtype=torch.float64)